katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import katalog_view

# TODO: Implement Routings Here
app_name = 'katalog'

urlpatterns = [
    path('', katalog_view, name='katalog_view'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include
from todolist.views import register 
from todolist.views import login_user
from todolist.views import logout_user

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
   
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import *

# TODO: Implement Routings Here
app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create-task'),
    path('selesai/<int:pk>', task_selesai, name='task-selesai'),
    path('undo/<int:pk>', undo_task, name='undo-task'),
    path('hapus/<int:pk>', hapus_task, name='hapus-task'),
    path('json/', todolist_ajax, name='todolist_ajax'),
    path('show/json/', show_todolist_ajax, name='show_todolist_ajax'),
    path('add/', add_task_ajax, name='add_task_ajax'),


]

todolist/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,)
    date = models.DateField(null=False, blank=False,auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from dataclasses import fields
from django import forms
from todolist.models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = {'title', 'description'}

todolist/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm

import datetime
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, HttpResponseBadRequest
from django.urls import reverse

from django.core import serializers

from todolist.forms import TaskForm
from todolist.models import Task

# Create your views here.

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:show_todolist"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    return redirect('todolist:login')

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    try: 
        user = request.user
        data = Task.objects.filter(user=user)
        context = {
            'todolist': data,
            'nama': user.username,
            'last_login': request.COOKIES['last_login'],
        }
        return render(request, "todolist.html", context)
    except KeyError:
        return redirect('todolist:login')

@login_required(login_url='/todolist/login/')
def todolist_ajax(request):
    user = request.user
    data = Task.objects.filter(user=user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_todolist_ajax(request):
    user = request.user
    context = {
        'nama': user.username,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "todolist_ajax.html", context)

def add_task_ajax(request):
    if request.method == 'POST':
        tasks = Task.objects.all()
        title = request.POST.get('title')
        description = request.POST.get('description')

        addedTask = Task.objects.create(
            title = title,
            description = description,
            date=datetime.datetime.now(),
            user=request.user,
        )

        addedTask.save()
        return HttpResponse("")
    
    return render(request, 'todolist_ajax.html', {'todolist':tasks})   


@login_required(login_url='/todolist/login/')
def create_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)

        form.instance.user = request.user
        form.instance.date = datetime.datetime.now()

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("todolist:show_todolist")) 
            #ganti  show_todolist_ajax saat demo ajax

    else:
        form = TaskForm()

        return render(request, 'create-task.html', {'form':form})

# @login_required(login_url='/todolist/login/')
# def add_task(request):
#     if request.method == 'POST':
#         form = TaskForm(request.POST)

#         form.instance.user = request.user
#         form.instance.date = datetime.datetime.now()

#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse("todolist:show_todolist"))

#     else:
#         form = TaskForm()

#         return render(request, 'create-task.html', {'form':form})

@login_required(login_url='/todolist/login/')
def task_selesai(request, pk):
    task = Task.objects.filter(id=pk).first()
    task.is_finished = True
    task.save()
    return HttpResponseRedirect(reverse("todolist:show_todolist"))

@login_required(login_url='/todolist/login/')
def undo_task(request, pk):
    task = Task.objects.filter(id=pk).first()
    task.is_finished = False
    task.save()
    return HttpResponseRedirect(reverse("todolist:show_todolist"))

@login_required(login_url='/todolist/login/')
def hapus_task(request, pk):
    Task.objects.filter(id=pk).first().delete()
    return HttpResponseRedirect(reverse("todolist:show_todolist"))
    

todolist/templates/create-task.html
{% extends 'base.html' %}

{% block meta %}
<script src="https://code.jquery.com/jquery-3.5.0.min.js"
        integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
{% endblock meta %}

{% block content %}

{% if user.is_authenticated %} 

    <div class="container">
        <h4 class="header-text py-4">Create Task 📌</h4>
        <div class="card mt-2">
            <h5 class="card-header text-bg-primary"><i class="bi bi-patch-check"></i> Add Task</h5>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <table class="table table-bordered">
                        {{form.as_table}}
                        <tr>
                            <td colspan="2">
                                <button class="btn btn-primary">Submit <i class="bi bi-send"></i></button>
                            
                            </td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
        <a href="{% url 'todolist:show_todolist' %}" class="btn btn-secondary active my-5" role="button" aria-pressed="true">Kembali</a>
    </div>

    {% if messages %}
    <ul>
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}     

{% else %}

    You are not logged in.

{% endif %}

{% endblock %}

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %} 
    <h1>Create task...</h1>
    <br/><br/>
    <div class="mb-3">
        <form method="POST">
            {% csrf_token %}
            <table>

                <tr>
                    <td>Title: </td>
                    <td>{{ form.title }}</td>
                </tr>
                        
                <tr>
                    <td>Description: </td>
                    <td>{{ form.description }}</td>
                </tr>

            </table>
            <button class="btn btn-primary">Post</button>
        </form>
    </div>

    {% if messages %}
    <ul>
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}     

{% else %}

    You are not logged in.

{% endif %}

{% endblock %}

todolist/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<link href="{% static 'style.css' %}" rel="stylesheet">

<header>
    <nav class="navbar navbar-light" style="background-color: skyblue; width: 100%;
    height: 80%;
    padding: 0;
    margin: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    margin-bottom: 50px;">
        <div class="container-fluid">
            <h1 class="navbar-brand mb-4 fw-normal font-family: 'Helvetica Neue';" style="text-decoration-color: white">Login User</h1>
        </div>
    </nav>
</header>

<body class="text-center">
    <div class = "login">
    
        <form class="form-login" method="POST" action="">
            {% csrf_token %}

            {% if messages %}
            {% for message in messages %}
                <div class="alert alert-danger">
                        <strong>{{ message|escape }}</strong>
                </div>
            {% endfor %}
            {% endif %}

            <table>
                <tr>
                    <td for="floatingInput">Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td for="floatingPassword">Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>
    
                <tr>
                    <td></td>
                    <td><input class="w-100 btn login_btn" type="submit" value="Login"></td>
                </tr>
            </table>
        </form>
    
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
            
        Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>
    
    </div>

</body>


{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}
{% block meta %}
<script src="https://code.jquery.com/jquery-3.5.0.min.js"
        integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
{% endblock meta %}
{% block content %}
<div class="container mx-6 mb-6">
    <p class="mt-5 mb-6">Hai, {{nama}}💙</p>

    <h1 class="my-4">🔖 To Do List</h1>
    <div class="card w-75 border-info my-4">
        <div class="card-body">
          <h5 class="card-title">Click the Button to create task!</h5>
          <p class="card-text text-primary">* Fill the form to add your task into the table.</p>
          <a href="{% url 'todolist:create-task' %}" class="btn btn-primary active my-3" role="button" aria-pressed="true">Create Task</a>
        </div>
      </div>
    
    {% for task in todolist %}
    <div class="card my-4">
        <div class="card-header">
            {{task.date}}
        </div>
        <div class="card-body" style="width:300px;">

          {% if task.is_finished %}
          <h6 class="text-success"><i class="bi bi-patch-check"></i> Task Selesai^^</h6>

          {% else %}
          <h6 class="text-secondary"><i class="bi bi-patch-exclamation"></i> Belum Selesai</h6>

          {% endif %}

          <h5 class="card-title">{{task.title}}</h5>
          <p class="card-text">{{task.description}}</p>
          <p>
            <a href="{% url 'todolist:task-selesai' pk=task.id %}" class="btn btn-primary active my-3" role="button" aria-pressed="true">Selesai</a>
            <a href="{% url 'todolist:undo-task' pk=task.id %}" class="btn btn-primary active my-3" role="button" aria-pressed="true">Belum Selesai</a>
            <a href="{% url 'todolist:hapus-task' pk=task.id %}"class="btn btn-danger active my-3" role="button" aria-pressed="true"><i class="bi bi-trash3"></i> Hapus</a>
          </p>
        </div>
    </div>
    {% endfor %}

    <a href="{% url 'todolist:logout' %}" class="btn btn-dark active my-5" role="button" aria-pressed="true">Logout</a>
   
</div>

{% endblock content %}

todolist/templates/todolist_ajax.html
{% extends 'base.html' %}

{% block meta %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</script>
<script>
  var counter = 0;
  function createTableAjax(){
    // clear table
    var tempCount = counter;

    $.get("http://localhost:8000/todolist/json/", function(data) {
      
      // fill table
      for(var i = counter; i < data.length; i++){
        var tr = document.createElement("tr");
        // var tdUser = document.createElement("td");
        // tdUser.append(data[i].fields.user);
        var tdDate = document.createElement("td");
        tdDate.append(data[i].fields.date);
        var tdTitle = document.createElement("td");
        tdTitle.append(data[i].fields.title);
        var tdDeskripsi = document.createElement("td");
        tdDeskripsi.append(data[i].fields.description);
        var tdFinished = document.createElement("td");
        tdFinished.append(data[i].fields.is_finished);
        
        // tr.append(tdUser);
        tr.append(tdDate);
        tr.append(tdTitle);
        tr.append(tdDeskripsi);
        tr.append(tdFinished);
        
        $(".table").append(tr);
        tempCount+=1;
      }
      counter = tempCount;
    });
  }
  
  $(document).ready(function(){
    $("#getData").click(function(){
      
      createTableAjax();

    });
  });

  $(document).on('submit', '#form_add_task', function(e) {
    e.preventDefault();
    $.ajax({
      type:"POST",
      url:"{% url 'todolist:add_task_ajax' %}",
      data:{
        title:$("#title-task").val(),
        description:$("#description-task").val(), 
        csrfmiddlewaretoken:'{{ csrf_token }}',
        action: 'post',
      },
      dataType: 'json',
    });
    setInterval('refreshPage()', 1000);
    createTableAjax();
  });

  function refreshPage() { 
        location.reload(); 
    }

</script>
{% endblock meta %}

{% block content %}
<h5>Nama: </h5>
<p>{{nama}}</p>

<h1>To Do List:</h1>

<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo">Add Task</button>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">New Task</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="POST" id="form_add_task" action="">
          {% csrf_token %}
          <div class="mb-3">
            <label for="title-name" class="col-form-label">Title:</label>
            <input type="text" class="form-control" id="title-task">
          </div>
          <div class="mb-3">
            <label for="description" class="col-form-label">Description:</label>
            <textarea class="form-control" id="description-task"></textarea>
          </div>
          <button type="submit" class="btn btn-primary">Post!</button>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<br/>
<br/>
<button><a href="{% url 'todolist:create-task' %}">Create Task</a></button><br/><br/>

<table class="table"> 
    <tr>
        <!-- <th>User</th> -->
        <th>Tanggal</th>
        <th>Judul</th>
        <th>Deskripsi</th>
        <th>Selesai</th>
    </tr>
    
</table>

<h5>Sesi terakhir login: {{ last_login }}</h5>
<button id="getData">Get Data</button>
<button><a href="{% url 'todolist:logout' %}">Logout</a></button>



{% endblock content %}